---
- name: Deploy application to production
  hosts: production
  become: yes
  vars:
    docker_image: "{{ lookup('env', 'DOCKER_IMAGE') }}"

  tasks:
    - name: Pull the Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run the application container
      docker_container:
        name: web_app
        image: "{{ docker_image }}"
        state: started
        recreate: yes
        ports:
          - "5000:5000"
        env:
          DATABASE_URL: "postgresql://postgres:aze123@db/playersdb"

    - name: Ensure database is running
      docker_container:
        name: db
        image: postgres:13-alpine
        state: started
        recreate: yes
        env:
          POSTGRES_DB: playersdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: aze123
        volumes:
          - postgres_data_prod:/var/lib/postgresql/data