version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE}
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:aze123@db/playersdb
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=playersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aze123
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

volumes:
  postgres_data_staging: