version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:aze123@db/playersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aze123
      - POSTGRES_DB=playersdb
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db", "5432", "--", "python", "app.py"]
    networks:
      - myapp-network


  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=playersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aze123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp-network

  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - myapp-network

  grafana:
    image: grafana/grafana:8.2.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_grafana_password
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - myapp-network

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - myapp-network

volumes:
  postgres_data:
  grafana_data:
  jenkins_home:

networks:
  myapp-network:
    driver: bridge