version: '3.8'
services:
  web:
    build: .
    image: adamelkt/player-app:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:aze123@db/playersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aze123
      - POSTGRES_DB=playersdb
    depends_on:
         - db
    networks:
         - myapp-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=playersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aze123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

volumes:
  postgres_data: